#!/bin/bash

azure account set RABO-D01-CloudDelivery
azure group deployment create --template-file azuredeploy-monitor-node.json \
    -e azuredeploy-monitor-node.parameters.json \
    -g RG-D01-APP-ONLINEDATASTORE-003 \
    -n MonitorNodeDeployment
